Upgrade to appwrite v1
lohanidamodar/flappwrite_account_kit pull request #14
Opened 2022-10-20 11:19 UTC by fballan93

2022-10-24 02:11 UTC, lohanidamodar requested changes
Let's also update this package version so that I can release.

2022-10-24 02:11 UTC, lohanidamodar commented on pubspec.yaml
> +  appwrite: ^8.0.0
Please use the latest version `8.1.0`

2022-10-24 06:31 UTC, fballan93 commented on pubspec.yaml
> +  appwrite: ^8.0.0
done

2022-10-26 11:29 UTC, fballan93 commented
Any thing stopping us from merging ?

2022-10-30 07:15 UTC, merged